#Database type, either sqlite or mysql
databasetype: sqlite
table-prefix: rpen_

#MySQL Connection settings, only needed when databasetype is set to mysql
mysql:
  host: localhost
  user: root
  password: 1234
  database: minecraft
  port: 3306

#Debug
debug: false

#ChatSettings
chatEnabled: true
rpRange: 35
whisperRange: 5
shoutRange: 50
logOOC: true
logRP: true

#MaxAge for if nothing is defined at the race:
MaxAge: 150
#Races
Races:
  Brother:
    Color: BLUE
    MaxAge: 150
    Plural: Brothers
  Human:
    Color: RED
    MaxAge: 150
    Plural: Humans
  Acolyte:
    Color: GREEN
    MaxAge: 150
    Plural: Acoli
  Exiled:
    Color: GOLD
    MaxAge: 150
    Plural: Exiles
  Lord:
    Color: RED
    MaxAge: 1000
    Plural: Lords
  Serf:
    Color: DARK_GRAY
    MaxAge: 150
    Plural: Serfs

#Nations
Nations:
  Tilicum:
    spawnX: 41870
    spawnY: 64
    spawnZ: -520
    spawnYaw: -90
    spawnPitch: 0
    spawnWorld: suffer
  Acolytes:
    spawnX: 41946
    spawnY: 64
    spawnZ: -541
    spawnYaw: 180
    spawnPitch: 0
    spawnWorld: suffer
    
# Speed in block per second for birds
speed: 20

#Max for countdown and rolls
maxRoll: 1000
maxCountdown: 20

#The cooldown in-between card changes in seconds
cardCooldown: 15

#Player health (20 is one full row of hearts and the default value)
playerHealth: 20

# What language messages are sent in
language: en_us